services:
  preferences_db:
    image: postgres:latest
    container_name: preferences_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: preferences_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_network

  api:
    build: ./backend
    container_name: api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - preferences_db
    networks:
      - backend_network
      - frontend_network
  
  telgram-bot:
    build: ./frontend
    env_file:
      - .env
    container_name: telegram-bot
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - frontend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
